# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0002_auto_20170613_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
